import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models.dart';
import '../store.dart';
import '../theme.dart';
import 'common.dart';
import 'forms.dart';

class AccountsScreen extends StatelessWidget { const AccountsScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Contas e cartões'),actions:[PopupMenuButton<String>(icon:const Icon(Icons.add_rounded),onSelected:(v)=>v=='account'?showAccountForm(c):showCardForm(c),itemBuilder:(_)=>const[PopupMenuItem(value:'account',child:Text('Nova conta')),PopupMenuItem(value:'card',child:Text('Novo cartão'))])]),body:ListView(padding:const EdgeInsets.all(14),children:[Text('CONTAS',style:eyebrowStyle(c)),const SizedBox(height:7),if(s.data.accounts.isEmpty)EmptyState(icon:Icons.account_balance_wallet_outlined,title:'Nenhuma conta',subtitle:'Adicione onde seu dinheiro fica.',actionLabel:'Nova conta',onAction:()=>showAccountForm(c))else ...s.data.accounts.map((a)=>Padding(padding:const EdgeInsets.only(bottom:8),child:SurfaceCard(padding:const EdgeInsets.all(14),child:Row(children:[const Icon(Icons.account_balance_wallet_outlined,color:FinoraColors.goldBright),const SizedBox(width:11),Expanded(child:Text(a.name,style:const TextStyle(fontSize:11.7,fontWeight:FontWeight.w900))),Text(money(c,a.balance),style:const TextStyle(color:FinoraColors.balance,fontSize:10.7,fontWeight:FontWeight.w900))])))),const SizedBox(height:12),Text('CARTÕES',style:eyebrowStyle(c)),const SizedBox(height:7),if(s.data.cards.isEmpty)EmptyState(icon:Icons.credit_card_outlined,title:'Nenhum cartão',subtitle:'Cadastre cartões para controlar fatura e limite.',actionLabel:'Novo cartão',onAction:()=>showCardForm(c))else ...s.data.cards.map((card)=>Padding(padding:const EdgeInsets.only(bottom:8),child:SurfaceCard(onTap:()=>Navigator.push(c,PremiumRoute(page:CardInvoiceScreen(cardId:card.id))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(card.name,style:const TextStyle(fontWeight:FontWeight.w900))),Text(money(c,card.used),style:const TextStyle(color:FinoraColors.expense,fontWeight:FontWeight.w900)),const Icon(Icons.chevron_right_rounded,size:18)]),const SizedBox(height:8),LinearProgressIndicator(value:card.limit<=0?0.0:(card.used/card.limit).clamp(0.0,1.0).toDouble(),minHeight:5,borderRadius:BorderRadius.circular(20),color:FinoraColors.expense,backgroundColor:Theme.of(c).dividerColor),const SizedBox(height:7),Text('Disponível ${money(c,card.available)} · fecha ${card.closeDay} · vence ${card.dueDay}',style:TextStyle(fontSize:8.6,color:Theme.of(c).colorScheme.onSurfaceVariant))]))))]));}}

class CardInvoiceScreen extends StatelessWidget { final String cardId; const CardInvoiceScreen({super.key,required this.cardId}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>(),card=s.findCard(cardId);if(card==null)return Scaffold(appBar:AppBar(title:const Text('Fatura')),body:const Center(child:Text('Cartão não encontrado.')));final tx=s.cardTransactionsForMonth(card.id,s.selectedMonth);return Scaffold(appBar:AppBar(title:Text(card.name)),body:ListView(padding:const EdgeInsets.all(14),children:[const MonthSwitcher(),const SizedBox(height:10),SurfaceCard(borderColor:FinoraColors.expense.withValues(alpha:.28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('FATURA ATUAL',style:eyebrowStyle(c)),const SizedBox(height:6),Text(money(c,card.used),style:const TextStyle(fontSize:27,color:FinoraColors.expense,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('Limite disponível ${money(c,card.available)} · fecha ${card.closeDay} · vence ${card.dueDay}',style:TextStyle(fontSize:9,color:Theme.of(c).colorScheme.onSurfaceVariant)),if(card.used>0&&s.data.accounts.isNotEmpty)...[const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>_pay(c,card),icon:const Icon(Icons.check_circle_outline_rounded),label:const Text('Pagar fatura')))] ])),const SizedBox(height:14),sectionTitle(c,'COMPRAS','Lançamentos no cartão'),const SizedBox(height:7),SurfaceCard(padding:const EdgeInsets.symmetric(horizontal:14,vertical:5),child:tx.isEmpty?const EmptyState(icon:Icons.credit_card_outlined,title:'Sem compras neste mês',subtitle:'Despesas deste cartão aparecerão aqui.'):Column(children:tx.map((e)=>TransactionTile(item:e,onTap:()=>showTransactionDetails(c,e))).toList()))]));}
Future<void> _pay(BuildContext c,CardItem card)async{final s=c.read<FinanceStore>();var account=s.data.accounts.first.name;final ok=await showDialog<bool>(context:c,builder:(d)=>StatefulBuilder(builder:(_,setLocal)=>AlertDialog(title:const Text('Pagar fatura'),content:DropdownButtonFormField<String>(initialValue:account,decoration:const InputDecoration(labelText:'Pagar usando'),items:s.data.accounts.map((e)=>DropdownMenuItem(value:e.name,child:Text(e.name))).toList(),onChanged:(v){if(v!=null)setLocal(()=>account=v);}),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Pagar'))])))??false;if(ok&&c.mounted){s.payInvoice(cardId:card.id,accountName:account);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Fatura paga')));}}
}
