import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../store.dart';
import '../theme.dart';
import 'common.dart';
import 'forms.dart';

class CategoriesScreen extends StatelessWidget { const CategoriesScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Categorias'),actions:[IconButton(onPressed:()=>showCategoryForm(c),icon:const Icon(Icons.add_rounded))]),body:ListView(padding:const EdgeInsets.all(14),children:[Text('DESPESAS PADRÃO',style:eyebrowStyle(c)),const SizedBox(height:7),SurfaceCard(child:Column(children:FinanceStore.defaultExpenseCategories.map((e)=>ListTile(dense:true,contentPadding:EdgeInsets.zero,title:Text(e,style:const TextStyle(fontSize:11)),trailing:const Text('Padrão',style:TextStyle(fontSize:8)))).toList())),const SizedBox(height:12),Text('PERSONALIZADAS',style:eyebrowStyle(c)),const SizedBox(height:7),SurfaceCard(child:s.data.categories.isEmpty?EmptyState(icon:Icons.category_outlined,title:'Nenhuma categoria personalizada',subtitle:'Crie categorias próprias para organizar melhor.',actionLabel:'Criar categoria',onAction:()=>showCategoryForm(c)):Column(children:s.data.categories.map((e)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(e.name,style:const TextStyle(fontSize:11.3,fontWeight:FontWeight.w800)),subtitle:Text(e.income?'Receita':'Despesa',style:const TextStyle(fontSize:8.5)),trailing:IconButton(onPressed:()=>s.deleteCategory(e.id),icon:const Icon(Icons.delete_outline_rounded)))).toList()))]));}}

class InsightsScreen extends StatelessWidget { const InsightsScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>(),rate=s.monthIncome==0?0:((s.monthBalance/s.monthIncome)*100).round(),cats=s.expensesByCategory.entries.toList()..sort((a,b)=>b.value.compareTo(a.value));final texts=['Taxa de economia: $rate%.',cats.isEmpty?'Registre despesas para identificar seu maior gasto.':'Maior categoria: ${cats.first.key}.',s.data.reserves.isEmpty?'Considere criar uma reserva de emergência.':'Reservas: ${money(c,s.reserveBalance)}.','${s.data.recurringRules.length} recorrência(s) e ${s.data.installmentPlans.length} parcelamento(s).'];return Scaffold(appBar:AppBar(title:const Text('Conselhos')),body:ListView.separated(padding:const EdgeInsets.all(14),itemCount:texts.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i)=>SurfaceCard(child:Row(children:[Container(width:40,height:40,decoration:BoxDecoration(color:FinoraColors.gold.withValues(alpha:.10),borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.lightbulb_outline_rounded,color:FinoraColors.goldBright)),const SizedBox(width:11),Expanded(child:Text(texts[i],style:const TextStyle(fontSize:10,height:1.4)))]))));}}

class SettingsScreen extends StatelessWidget { const SettingsScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Configurações')),body:ListView(padding:const EdgeInsets.all(14),children:[SurfaceCard(child:Column(children:[SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Tema OLED',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900)),value:s.data.darkMode,onChanged:s.setDarkMode),const Divider(),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Ocultar valores',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900)),value:s.data.privacyMode,onChanged:s.setPrivacyMode)])),const SizedBox(height:10),SurfaceCard(child:Column(children:[ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.science_outlined,color:FinoraColors.investment),title:const Text('Carregar dados de demonstração'),onTap:()=>_confirm(c,'Carregar demonstração?','Os dados atuais serão substituídos.',s.loadDemo)),const Divider(),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.cleaning_services_outlined,color:FinoraColors.expense),title:const Text('Limpar todos os dados'),onTap:()=>_confirm(c,'Limpar tudo?','Todos os dados financeiros serão apagados.',s.clearForRealUse))]))]));}
Future<void> _confirm(BuildContext c,String title,String body,VoidCallback action)async{final ok=await showDialog<bool>(context:c,builder:(d)=>AlertDialog(title:Text(title),content:Text(body),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Confirmar'))]))??false;if(ok)action();}
}
