import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../store.dart';
import '../theme.dart';
import 'common.dart';
import 'forms.dart';

class GoalsScreen extends StatelessWidget { const GoalsScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Metas'),actions:[IconButton(onPressed:()=>showGoalForm(c),icon:const Icon(Icons.add_rounded))]),body:s.data.goals.isEmpty?Center(child:EmptyState(icon:Icons.track_changes_rounded,title:'Nenhuma meta criada',subtitle:'Crie um objetivo e acompanhe seu progresso.',actionLabel:'Nova meta',onAction:()=>showGoalForm(c))):ListView.separated(padding:const EdgeInsets.all(14),itemCount:s.data.goals.length,separatorBuilder:(_,__)=>const SizedBox(height:9),itemBuilder:(_,i){final g=s.data.goals[i],ratio=g.target<=0?0.0:(g.saved/g.target).clamp(0.0,1.0).toDouble(),remain=(g.target-g.saved).clamp(0.0,double.infinity).toDouble(),now=DateTime.now(),months=((g.deadline.year-now.year)*12+g.deadline.month-now.month).clamp(1,1200),monthly=remain/months;return SurfaceCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(g.name,style:const TextStyle(fontWeight:FontWeight.w900))),Text('${(ratio*100).round()}%',style:const TextStyle(color:FinoraColors.goal,fontWeight:FontWeight.w900))]),const SizedBox(height:9),Text('${money(c,g.saved)} / ${money(c,g.target)}',style:const TextStyle(color:FinoraColors.goal,fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:9),LinearProgressIndicator(value:ratio,minHeight:6,borderRadius:BorderRadius.circular(20),color:FinoraColors.goal,backgroundColor:Theme.of(c).dividerColor),const SizedBox(height:9),Text(remain<=0?'Meta concluída.':'Para atingir até ${shortDate(g.deadline)}: cerca de ${money(c,monthly)}/mês.',style:const TextStyle(fontSize:9.2)),Row(children:[Expanded(child:Text('Falta ${money(c,remain)}',style:TextStyle(fontSize:8.8,color:Theme.of(c).colorScheme.onSurfaceVariant))),TextButton(onPressed:()=>showContribution(c,true,g.id),child:const Text('+ Aporte'))])])) ;}));}}
class ReservesScreen extends StatelessWidget { const ReservesScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Reservas'),actions:[IconButton(onPressed:()=>showReserveForm(c),icon:const Icon(Icons.add_rounded))]),body:s.data.reserves.isEmpty?Center(child:EmptyState(icon:Icons.shield_outlined,title:'Nenhuma reserva criada',subtitle:'Separe sua proteção financeira das metas.',actionLabel:'Criar reserva',onAction:()=>showReserveForm(c))):ListView.separated(padding:const EdgeInsets.all(14),itemCount:s.data.reserves.length,separatorBuilder:(_,__)=>const SizedBox(height:9),itemBuilder:(_,i){final r=s.data.reserves[i],ratio=r.target<=0?0.0:(r.saved/r.target).clamp(0.0,1.0).toDouble();return SurfaceCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(r.name,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:9),Text('${money(c,r.saved)} / ${money(c,r.target)}',style:const TextStyle(color:FinoraColors.warning,fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:9),LinearProgressIndicator(value:ratio,minHeight:6,borderRadius:BorderRadius.circular(20),color:FinoraColors.warning,backgroundColor:Theme.of(c).dividerColor),Row(children:[Expanded(child:Text('${r.months} meses de proteção',style:TextStyle(fontSize:8.8,color:Theme.of(c).colorScheme.onSurfaceVariant))),TextButton(onPressed:()=>showContribution(c,false,r.id),child:const Text('+ Aporte'))])])) ;}));}}
class InvestmentsScreen extends StatelessWidget { const InvestmentsScreen({super.key}); @override Widget build(BuildContext c){final s=c.watch<FinanceStore>();return Scaffold(appBar:AppBar(title:const Text('Investimentos'),actions:[IconButton(onPressed:()=>showInvestmentForm(c),icon:const Icon(Icons.add_rounded))]),body:s.data.investments.isEmpty?Center(child:EmptyState(icon:Icons.show_chart_rounded,title:'Carteira vazia',subtitle:'Adicione seus investimentos para acompanhar o patrimônio.',actionLabel:'Adicionar',onAction:()=>showInvestmentForm(c))):ListView(padding:const EdgeInsets.all(14),children:[SurfaceCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('TOTAL INVESTIDO',style:eyebrowStyle(c)),const SizedBox(height:6),Text(money(c,s.investmentBalance),style:const TextStyle(color:FinoraColors.investment,fontSize:23,fontWeight:FontWeight.w900))])),const SizedBox(height:10),SurfaceCard(child:Column(children:s.data.investments.map((e)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(e.name,style:const TextStyle(fontSize:11.4,fontWeight:FontWeight.w800)),subtitle:Text('${e.assetClass} · ${e.estimatedReturn.toStringAsFixed(1)}%',style:const TextStyle(fontSize:8.6)),trailing:Text(money(c,e.amount),style:const TextStyle(color:FinoraColors.investment,fontSize:10.4,fontWeight:FontWeight.w900)))).toList()))]));}}
