import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'store.dart';
import 'theme.dart';

class OnboardingScreen extends StatefulWidget{const OnboardingScreen({super.key});@override State<OnboardingScreen> createState()=>_OnboardingScreenState();}
class _OnboardingScreenState extends State<OnboardingScreen>{
  final pages=PageController();final account=TextEditingController(text:'Conta principal');final balance=TextEditingController(text:'0');int page=0;String goal='Controlar gastos';
  @override void dispose(){pages.dispose();account.dispose();balance.dispose();super.dispose();}
  void next(){if(page<2){pages.nextPage(duration:const Duration(milliseconds:320),curve:Curves.easeOutCubic);return;}final v=double.tryParse(balance.text.replaceAll(',','.'))??0;context.read<FinanceStore>().finishOnboarding(account.text,v,goal);}
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[
    Padding(padding:const EdgeInsets.fromLTRB(20,18,20,8),child:Row(children:[Container(width:42,height:42,alignment:Alignment.center,decoration:BoxDecoration(gradient:const LinearGradient(colors:[FinoraColors.goldBright,FinoraColors.gold]),borderRadius:BorderRadius.circular(14)),child:const Text('F',style:TextStyle(color:Colors.black,fontWeight:FontWeight.w900,fontSize:18))),const Spacer(),Text('${page+1}/3',style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:Theme.of(context).colorScheme.onSurfaceVariant))])),
    Expanded(child:PageView(controller:pages,onPageChanged:(v)=>setState(()=>page=v),children:[welcome(context),accountPage(context),goalPage(context)])),
    Padding(padding:const EdgeInsets.fromLTRB(20,8,20,20),child:Column(children:[Row(children:List.generate(3,(i)=>AnimatedContainer(duration:const Duration(milliseconds:200),margin:const EdgeInsets.only(right:6),width:i==page?24:7,height:7,decoration:BoxDecoration(color:i==page?FinoraColors.goldBright:Theme.of(context).dividerColor,borderRadius:BorderRadius.circular(20))))),const SizedBox(height:18),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:next,child:Text(page==2?'Começar a usar':'Continuar')))]))
  ])));
  Widget welcome(BuildContext c)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:66,height:66,decoration:BoxDecoration(color:FinoraColors.gold.withOpacity(.12),borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.account_balance_wallet_rounded,color:FinoraColors.goldBright,size:32)),const SizedBox(height:28),const Text('Seu dinheiro,\nmais claro.',style:TextStyle(fontSize:34,height:1.03,fontWeight:FontWeight.w900,letterSpacing:-1.1)),const SizedBox(height:14),Text('Controle gastos, planeje o mês e acompanhe metas sem transformar sua vida financeira em uma planilha complicada.',style:TextStyle(fontSize:13,height:1.55,color:Theme.of(c).colorScheme.onSurfaceVariant))]));
  Widget accountPage(BuildContext c)=>Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sua primeira conta',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('Comece com a conta que você mais usa. Outras podem ser adicionadas depois.',style:TextStyle(fontSize:12,height:1.5,color:Theme.of(c).colorScheme.onSurfaceVariant)),const SizedBox(height:24),TextField(controller:account,decoration:const InputDecoration(labelText:'Nome da conta',prefixIcon:Icon(Icons.account_balance_wallet_outlined))),const SizedBox(height:12),TextField(controller:balance,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Saldo atual',prefixIcon:Icon(Icons.attach_money_rounded)))]));
  Widget goalPage(BuildContext c){const items=['Controlar gastos','Economizar','Criar reserva','Planejar melhor'];return Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sua prioridade',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('Isso ajuda o Finora a destacar as informações mais importantes.',style:TextStyle(fontSize:12,height:1.5,color:Theme.of(c).colorScheme.onSurfaceVariant)),const SizedBox(height:22),...items.map((x)=>Padding(padding:const EdgeInsets.only(bottom:9),child:InkWell(onTap:()=>setState(()=>goal=x),borderRadius:BorderRadius.circular(17),child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:goal==x?FinoraColors.gold.withOpacity(.12):Theme.of(c).cardColor,borderRadius:BorderRadius.circular(17),border:Border.all(color:goal==x?FinoraColors.goldBright:Theme.of(c).dividerColor)),child:Row(children:[Icon(goal==x?Icons.radio_button_checked_rounded:Icons.radio_button_off_rounded,color:goal==x?FinoraColors.goldBright:Theme.of(c).colorScheme.onSurfaceVariant),const SizedBox(width:12),Text(x,style:const TextStyle(fontWeight:FontWeight.w800))])))))]));}
}
